# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CodeCavern
author:
  name: Jyrki Heinonen
  email: jyrki.heinonen@iki.fi
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codecavern.heinoset.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JyrkiH
github_username:  JyrkiHei

# Build settings
#theme: minimal-mistakes-jekyll
theme: "minima"
plugins:
- jekyll-include-cache
- jekyll-feed
- jekyll-seo-tag

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# excerpt_separator: <!--more-->
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 5 # amount of posts to show
paginate_path: /page:num/

google_analytics: G-4PZMDEERWN

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: JyrkiH
    github:  JyrkiHei
    facebook: JyrkiHei
    linkedin: jyrki-heinonen

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true